env: buttons

env_args:
  max_episode_length: 1000
  initial_rm_states: [5, 3, 1]
  joint_rm_file: "buttons_aux_rm.txt"
  team_rm_file: "team_buttons_rm.txt"
  manager_epsilon: 0
  manager_epsilon_decay: 0.95
  manager_assignment_method: "epsilon_greedy"


mask_flag: False
global_state_flag: False
opp_action_in_cc: True
agent_level_batch_update: False
# local_dir: /Users/nikhil/Desktop/RL_Research/examples/exp_results_2